FitnessEvents/Models/FitnessEvent.cs
namespace FitnessEvents.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class FitnessEvent
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Event name")]
        public string EventName { get; set; }

        [Required]
        [Display(Name = "Event Details")]
        public string EventDetails { get; set; }

        [Required]
        [Display(Name = "Event Date")]
        [DataType(DataType.Date)]
        public DateTime EventDate { get; set; }

        [Required]
        [Display(Name = "Event Type")]
        public string EventType { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Posted Date")]
        public DateTime PostedDate { get; set; }

        [Required]
        [Display(Name = "Image Upload")]
        public string ImageUrl { get; set; }

        [Required]
        [Display(Name = "Organizer Name")]
        [StringLength(128)]
        public string ApplicationUserId { get; set; }
    }
}

FitnessEvents/Controllers/EventRegistrationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FitnessEvents.Models;

namespace FitnessEvents.Controllers
{
    public class EventRegistrationsController : Controller
    {
        private FitnessEvents_Models db = new FitnessEvents_Models();

        // GET: EventRegistrations
        [Authorize]
        public ActionResult Index()
        {
            return View(db.EventRegistrations.ToList());
        }

        // GET: EventRegistrations/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventRegistration eventRegistration = db.EventRegistrations.Find(id);
            if (eventRegistration == null)
            {
                return HttpNotFound();
            }
            return View(eventRegistration);
        }

        // GET: EventRegistrations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EventRegistrations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FirstName,LastName,DOB,Email,Address,SpecialRequest,EventId")] EventRegistration eventRegistration)
        {
            if (ModelState.IsValid)
            {
                ViewBag.EventId = new SelectList(db.FitnessEvents, "Id", "EventName");
                db.EventRegistrations.Add(eventRegistration);
                db.SaveChanges();
                return RedirectToAction("SuccessMessage");
            }

            return View(eventRegistration);
        }

        // GET: EventRegistrations/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventRegistration eventRegistration = db.EventRegistrations.Find(id);
            if (eventRegistration == null)
            {
                return HttpNotFound();
            }
            return View(eventRegistration);
        }

        // POST: EventRegistrations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FirstName,LastName,DOB,Email,Address,SpecialRequest,EventId")] EventRegistration eventRegistration)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eventRegistration).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(eventRegistration);
        }

        // GET: EventRegistrations/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventRegistration eventRegistration = db.EventRegistrations.Find(id);
            if (eventRegistration == null)
            {
                return HttpNotFound();
            }
            return View(eventRegistration);
        }

        // POST: EventRegistrations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EventRegistration eventRegistration = db.EventRegistrations.Find(id);
            db.EventRegistrations.Remove(eventRegistration);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult SuccessMessage()
        {
            return View();

        }
    }
}

FitnessEvents/Controllers/FitnessEventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FitnessEvents.Models;

namespace FitnessEvents.Controllers
{
    public class FitnessEventsController : Controller
    {
        private FitnessEvents_Models db = new FitnessEvents_Models();

        // GET: FitnessEvents
        public ActionResult Index()
        {
            return View(db.FitnessEvents.ToList());
        }

        [AllowAnonymous]
        // GET: FitnessEvents/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FitnessEvent fitnessEvent = db.FitnessEvents.Find(id);
            if (fitnessEvent == null)
            {
                return HttpNotFound();
            }
            return View(fitnessEvent);
        }

        [Authorize]
        // GET: FitnessEvents/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FitnessEvents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,EventName,EventDetails,EventDate,EventType,PostedDate,ApplicationUserId")]
        FitnessEvent fitnessEvent, HttpPostedFileBase postedFile)
        {


            ModelState.Clear();
            var myUniqueFileName = string.Format(@"{0}", Guid.NewGuid());
            fitnessEvent.ImageUrl = myUniqueFileName;
            TryValidateModel(fitnessEvent);

            if (ModelState.IsValid)
            {
                string serverPath = Server.MapPath("~/Uploads/");
               // string fileExtension = ImageUrl.GetExtension(postedFile.FileName);
                string filePath = fitnessEvent.ImageUrl + ".jpg";
                fitnessEvent.ImageUrl = filePath;
                postedFile.SaveAs(serverPath + fitnessEvent.ImageUrl);

                db.FitnessEvents.Add(fitnessEvent);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(fitnessEvent);
        }

        // GET: FitnessEvents/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FitnessEvent fitnessEvent = db.FitnessEvents.Find(id);
            if (fitnessEvent == null)
            {
                return HttpNotFound();
            }
            return View(fitnessEvent);
        }

        // POST: FitnessEvents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,EventName,EventDetails,EventDate,EventType,PostedDate,ApplicationUserId")]
        FitnessEvent fitnessEvent, HttpPostedFileBase postedFile)
        {
            if (ModelState.IsValid)
            {
                if (postedFile != null)
                {
                    string serverPath = Server.MapPath("~/Uploads/");
                    // string fileExtension = ImageUrl.GetExtension(postedFile.FileName);
                    string filePath = fitnessEvent.ImageUrl + ".jpg";
                    fitnessEvent.ImageUrl = filePath;
                    postedFile.SaveAs(serverPath + fitnessEvent.ImageUrl);
                }

                
                db.Entry(fitnessEvent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(fitnessEvent);
        }

        // GET: FitnessEvents/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FitnessEvent fitnessEvent = db.FitnessEvents.Find(id);
            if (fitnessEvent == null)
            {
                return HttpNotFound();
            }
            return View(fitnessEvent);
        }

        // POST: FitnessEvents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FitnessEvent fitnessEvent = db.FitnessEvents.Find(id);
            db.FitnessEvents.Remove(fitnessEvent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FitnessEvents/Views/FitnessEvents/Create.cshtml
@model FitnessEvents.Models.FitnessEvent

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "FitnessEvents", FormMethod.Post,
                     new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FitnessEvent</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EventName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventDetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventDetails, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventDetails, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
           
            <label class= "control-label col-md-2" for="Name">Browse Image</label>
            <div class="col-md-10">
                <input type="file" name="postedFile" class="btn btn-default" accept="image/jpeg"/>
                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationUserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicationUserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicationUserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FitnessEvents/Views/FitnessEvents/Delete.cshtml
@model FitnessEvents.Models.FitnessEvent

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FitnessEvent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EventName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDetails)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDetails)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationUserId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FitnessEvents/Views/FitnessEvents/Details.cshtml
@using Microsoft.AspNet.Identity
@model FitnessEvents.Models.FitnessEvent

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>FitnessEvent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EventName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDetails)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDetails)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostedDate)
        </dd>

        <dd>
            <img class="img-thumbnail" src='@Url.Content("~/Uploads/" + @Model.ImageUrl)' />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationUserId)
        </dd>

    </dl>
</div>
<p>
    @if (Request.IsAuthenticated)
    {<a href="@Url.Action("Edit", "FitnessEvents", new { id = Model.Id })" class="btn btn-warning">Edit</a> 
    }
        
    <a href="@Url.Action("Index", "FitnessEvents", new { id = Model.Id })" class="btn btn-warning">Back to list</a>
    <a href="@Url.Action("Create", "EventRegistrations", new { id = Model.Id })" class="btn btn-success">Register</a>

</p>

FitnessEvents/Views/FitnessEvents/Edit.cshtml
@model FitnessEvents.Models.FitnessEvent

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FitnessEvent</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.EventName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventDetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventDetails, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventDetails, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <img class="img-thumbnail" src='@Url.Content("~/Uploads/" + @Model.ImageUrl)' />
            <div class="col-md-10">
                <label class="control-label col-md-2" for="Name">Browse Image</label>
                <input type="file" name="postedFile" class="btn btn-default" accept="image/jpeg" />
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationUserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicationUserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicationUserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FitnessEvents/Views/FitnessEvents/Index.cshtml
@using Microsoft.AspNet.Identity
@model IEnumerable<FitnessEvents.Models.FitnessEvent>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Fitness events around you</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EventName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventDetails)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationUserId)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EventName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventDetails)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostedDate)
            </td>
            <td>
                <img class="img-thumbnail" src='@Url.Content("~/Uploads/" + item.ImageUrl)' />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicationUserId)
            </td>
            <td>

                <a href="@Url.Action("Details", "FitnessEvents", new { id = item.Id })" class="btn btn-primary">Details</a>
                <a href="@Url.Action("Create", "EventRegistrations", new { id = item.Id })" class="btn btn-success">Register</a>

                @if (Request.IsAuthenticated)
                {
                    if (ViewContext.HttpContext.User.IsInRole("Admin"))
                    {
                        <a href="@Url.Action("Edit", "FitnessEvents", new { id = item.Id })" class="btn btn-warning">Edit</a>
                        <a href="@Url.Action("Delete", "FitnessEvents", new { id = item.Id })" class="btn btn-danger">Delete</a>



                    }

                    <a href="@Url.Action("Index", "EventRegistrations", new { id = item.Id })" class="btn btn-primary">View Registrations</a>
                }

                </td>
        </tr>
    }

</table>